version: "3.7"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/opt/webapp
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "8080:8000"
    env_file:
      - ./.env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: postgres:12.0-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
volumes:
  postgres_data:
